
language: ruby
cache: bundler
python:
  - 3.5
rvm:
  - 2.3
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get install -y python3
  - python3 taggenerator.py

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  target-branch: travis-trigger
  keep-history: true
  on:
    branch: master