
language: ruby
python:
  - 3.5
rvm:
  - 2.1
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - sudo apt-get install -y python3
  - python3 taggenerator.py