
language: ruby
cache: bundler
python:
  - 3.8
rvm:
  - 2.7
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get install -y python3
  - python3 taggenerator.py
